export const LOGIN_REQ = 'LOGIN_REQ'
export const LOGIN_FETCHING = 'LOGIN_FETCHING'
export const LOGIN = 'LOGIN'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const LOGOUT = 'LOGOUT'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'

export const EMP_REQ = 'EMP_REQ'
export const EMP_FETCHING = 'EMP_FETCHING'
export const EMP_FAILED = 'EMP_FAILED'
export const EMP_SUCCESS = 'EMP_SUCCESS'

export const OFFICE_REQ = 'OFFICE_REQ'
export const OFFICE_FETCHING = 'OFFICE_FETCHING'
export const OFFICE_SUCCESS = 'OFFICE_SUCCESS'

export const COMP_REQ = 'COMP_REQ'
export const COMP_FETCHING = 'COMP_FETCHING'
export const COMP_SUCCESS = 'COMP_SUCCESS'

export const GENDER_REQ = 'GENDER_REQ'
export const GENDER_FETCHING = 'GENDER_FETCHING'
export const GENDER_SUCCESS = 'GENDER_SUCCESS'

export const TITLE_NAME_REQ = 'TITLE_NAME_REQ'
export const TITLE_NAME_FETCHING = 'TITLE_NAME_FETCHING'
export const TITLE_NAME_SUCCESS = 'TITLE_NAME_SUCCESS'

export const HOSPITAL_REQ = 'HOSPITAL_REQ'
export const HOSPITAL_FETCHING = 'HOSPITAL_FETCHING'
export const HOSPITAL_SUCCESS = 'HOSPITAL_SUCCESS'

export const WORK_TIME_REQ = 'WORK_TIME_REQ'
export const WORK_TIME_FETCHING = 'WORK_TIME_FETCHING'
export const WORK_TIME_SUCCESS = 'WORK_TIME_SUCCESS'